# Generated by Django 3.1.2 on 2020-10-09 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='filter',
            new_name='choice',
        ),
    ]
